# See: https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates#about-the-dependabotyml-file
version: 2

updates:
  # Configure check for outdated GitHub Actions actions in workflows.
  # See: https://docs.github.com/en/github/administering-a-repository/keeping-your-actions-up-to-date-with-dependabot
  - package-ecosystem: github-actions
    directory: /.github/workflows/
    schedule:
      interval: daily
    labels:
      - "topic: infrastructure"
    assignees:
      - per1234

  # Configure check for outdated GitHub Actions actions in workflow templates.
  - package-ecosystem: github-actions
    directory: /workflow-templates/
    schedule:
      interval: daily
    labels:
      - "topic: infrastructure"
    assignees:
      - per1234

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    labels:
      - "topic: infrastructure"
    assignees:
      - per1234
