# Source: https://github.com/arduino/.github/blob/master/workflow-templates/check-python.md
name: Check Python

# See: https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows
on:
  push:
    paths:
      - ".github/workflows/check-python.yml"
      - "**/.flake8"
      - "**/setup.cfg"
      - "**/tox.ini"
      - "**/pyproject.toml"
      - "**.py"
  pull_request:
    paths:
      - ".github/workflows/check-python.yml"
      - "**/.flake8"
      - "**/setup.cfg"
      - "**/tox.ini"
      - "**/pyproject.toml"
      - "**.py"
  schedule:
    # Run every Tuesday at 8 AM UTC to catch breakage caused by changes to flake8.
    - cron: "0 8 * * TUE"
  workflow_dispatch:
  repository_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get week number for use in cache key
        id: get-date
        run: |
          echo "::set-output name=week-number::$(date --utc '+%V')"

      - name: Load dependencies cache
        uses: actions/cache@v2.1.4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-flake8-${{ steps.get-date.outputs.week-number }}
          restore-keys: |
            ${{ runner.os }}-pip-flake8-

      - name: Install flake8
        run: |
          python -m pip install --upgrade pip
          python -m pip install --quiet flake8
          python -m pip install --quiet pep8-naming

      - name: Run flake8
        run: python -m flake8 --show-source

  formatting:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v2

      - name: Check formatting
        uses: psf/black@stable
