# Source: https://github.com/arduino/.github/blob/master/workflow-templates/check-mkdocs.md
name: Check documentation website

# See: https://docs.github.com/en/actions/reference/events-that-trigger-workflows
on:
  push:
    paths:
      - ".github/workflows/check-mkdocs.yml"
      - "mkdocs.yml"
      - "docs/**"
  pull_request:
    paths:
      - ".github/workflows/check-mkdocs.yml"
      - "mkdocs.yml"
      - "docs/**"
  schedule:
    # Run every Tuesday at 8 AM UTC to catch breakage caused by changes to external tools.
    - cron: "0 8 * * TUE"
  workflow_dispatch:
  repository_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m pip install --quiet --upgrade pip
          python -m pip install --quiet --requirement "${{ github.workspace }}/docs/requirements.txt"

      - name: Build website
        run: python -m mkdocs build --strict
