# Source: https://github.com/per1234/.github/blob/main/workflow-templates/check-python.md
name: Check Python

# See: https://docs.github.com/en/actions/reference/events-that-trigger-workflows
on:
  push:
    paths:
      - ".github/workflows/check-python.ya?ml"
      - "**/.flake8"
      - "**/setup.cfg"
      - "**/tox.ini"
      - "**/poetry.lock"
      - "**/pyproject.toml"
      - "**.py"
  pull_request:
    paths:
      - ".github/workflows/check-python.ya?ml"
      - "**/.flake8"
      - "**/setup.cfg"
      - "**/tox.ini"
      - "**/poetry.lock"
      - "**/pyproject.toml"
      - "**.py"
  schedule:
    # Run every Tuesday at 8 AM UTC to catch breakage caused by changes to flake8.
    - cron: "0 8 * * TUE"
  workflow_dispatch:
  repository_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install flake8
        run: |
          python -m pip install --upgrade pip
          python -m pip install --quiet flake8
          python -m pip install --quiet pep8-naming

      - name: Run flake8
        run: python -m flake8 --show-source

  formatting:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v3

      - name: Check formatting
        uses: psf/black@stable
