# Source: https://github.com/per1234/.github/blob/main/workflow-templates/check-cpp.md
name: Check C++

# See: https://docs.github.com/en/actions/reference/events-that-trigger-workflows
on:
  push:
    paths:
      - ".github/workflows/check-cpp.ya?ml"
      - ".clang-format"
      - "**.ino"
      - "**.hh?"
      - "**.hpp"
      - "**.hxx"
      - "**.cpp"
      - "**.cc?"
      - "**.cxx"
      - "**.cp"
      - "**.ipp"
      - "**.ii"
      - "**.ixx"
      - "**.inl"
      - "**.tpp"
      - "**.txx"
      - "**.tpl"
  pull_request:
    paths:
      - ".github/workflows/check-cpp.ya?ml"
      - ".clang-format"
      - "**.ino"
      - "**.hh?"
      - "**.hpp"
      - "**.hxx"
      - "**.cpp"
      - "**.cc?"
      - "**.cxx"
      - "**.cp"
      - "**.ipp"
      - "**.ii"
      - "**.ixx"
      - "**.inl"
      - "**.tpp"
      - "**.txx"
      - "**.tpl"
  workflow_dispatch:
  repository_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Format
        uses: DoozyX/clang-format-lint-action@v0.13
        with:
          clangFormatVersion: 11
          exclude: ./.git
          extensions: c,c++,cc,cp,cpp,cxx,h,h++,hh,hpp,hxx,ii,ino,inl,ipp,ixx,tpl,tpp,txx

      - name: Check formatting
        run: git diff --color --exit-code
