# Source: https://github.com/arduino/.github/blob/master/workflow-templates/compile-sketches.md
name: Compile Sketches

# See: https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows
on:
  push:
    paths-ignore:
      - ".github/**"
      - "!.github/workflows/compile-sketches.yml"
      - "**.adoc"
      - "**.jpg"
      - "**.md"
      - "**.png"
      - "**.txt"
  pull_request:
    paths-ignore:
      - ".github/**"
      - "!.github/workflows/compile-sketches.yml"
      - "**.adoc"
      - "**.jpg"
      - "**.md"
      - "**.png"
      - "**.txt"
  schedule:
    # Run every Tuesday at 8 AM UTC to catch breakage caused by changes to external resources (libraries, platforms).
    - cron: "0 8 * * TUE"
  workflow_dispatch:
  repository_dispatch:

jobs:
  build:
    name: ${{ matrix.board.fqbn }}
    runs-on: ubuntu-latest

    env:
      SKETCHES_REPORTS_PATH: sketches-reports

    strategy:
      fail-fast: false

      matrix:
        board:
          # TODO: Add list of boards to compile for here:
          - fqbn: arduino:avr:uno
            # TODO: Define the board's platform dependencies here.
            # See: https://github.com/arduino/compile-sketches#platforms
            platforms: |
              - name: arduino:avr

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get week number for use in cache keys
        id: get-date
        run: |
          echo "::set-output name=week-number::$(date --utc '+%V')"

      - name: Load dependencies cache for the arduino/compile-sketches action
        uses: actions/cache@v2
        with:
          path: ~/work/_actions/arduino/compile-sketches/main/compilesketches/.venv
          # The key name uses the week number to cause it to update weekly.
          key: ${{ runner.os }}-arduino-compile-sketches-action-venv-${{ steps.get-date.outputs.week-number }}
          # The updated cache will be based on the existing one.
          restore-keys: |
            ${{ runner.os }}-arduino-compile-sketches-action-venv-

      - name: Load dependencies cache for the board
        uses: actions/cache@v2
        with:
          path: ~/.arduino15/staging
          key: ${{ runner.os }}-arduino-data-${{ matrix.board.platforms }}-${{ steps.get-date.outputs.week-number }}
          restore-keys: |
            ${{ runner.os }}-arduino-data-${{ matrix.board.platforms }}-

      - name: Compile examples
        uses: arduino/compile-sketches@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fqbn: ${{ matrix.board.fqbn }}
          platforms: ${{ matrix.board.platforms }}
          libraries: |
            # Disable the default behavior of installing the repository as a library.
            -
            # Additional library dependencies can be listed here.
            # See: https://github.com/arduino/compile-sketches#libraries
          sketch-paths: |
            - ${{ github.workspace }}
          enable-deltas-report: true
          sketches-report-path: ${{ env.SKETCHES_REPORTS_PATH }}

      - name: Save sketches report as workflow artifact
        uses: actions/upload-artifact@v2
        with:
          if-no-files-found: error
          path: ${{ env.SKETCHES_REPORTS_PATH }}
          name: ${{ env.SKETCHES_REPORTS_PATH }}
