# Source: https://github.com/per1234/.github/blob/main/workflow-templates/test-javascript-jest-task.md
name: Test JavaScript

env:
  # See: https://github.com/actions/setup-node/#readme
  NODE_VERSION: 16.x

on:
  push:
    paths:
      - ".github/workflows/test-javascript-jest-task.ya?ml"
      - "jest.config.[jt]s"
      - "lerna.json"
      - "package.json"
      - "package-lock.json"
      - "Taskfile.ya?ml"
      - "tsconfig.json"
      - "yarn.lock"
      - "**.[jt]sx?"
  pull_request:
    paths:
      - ".github/workflows/test-javascript-jest-task.ya?ml"
      - "jest.config.[jt]s"
      - "lerna.json"
      - "package.json"
      - "package-lock.json"
      - "Taskfile.ya?ml"
      - "tsconfig.json"
      - "yarn.lock"
      - "**.[jt]sx?"
  workflow_dispatch:
  repository_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3.0.0
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Task
        uses: arduino/setup-task@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          version: 3.x

      - name: Run tests
        run: task js:test
