# See: https://black.readthedocs.io/en/stable/pyproject_toml.html
# The code style defined in this file is the official standardized style to be used in all Arduino projects and should
# not be modified.

[tool.black]
line-length = 120
