# See: https://taskfile.dev/#/usage
version: "3"

tasks:
  # Source: https://github.com/per1234/.github/blob/main/workflow-templates/assets/check-npm-task/Taskfile.yml
  npm:validate:
    desc: Validate npm configuration files against their JSON schema
    vars:
      # Last version with support for draft-04, used by the `package.json` schema
      AJV_CLI_VERSION: 3.3.0
      # Source: https://github.com/SchemaStore/schemastore/blob/master/src/schemas/json/package.json
      SCHEMA_URL: https://json.schemastore.org/package.json
      SCHEMA_PATH:
        sh: mktemp -t package-json-schema-XXXXXXXXXX.json
      INSTANCE_PATH: "**/package.json"
    cmds:
      - wget --quiet --output-document="{{.SCHEMA_PATH}}" {{.SCHEMA_URL}}
      - |
        npx ajv-cli@{{.AJV_CLI_VERSION}} validate \
          --all-errors \
          -s "{{.SCHEMA_PATH}}" \
          -d "{{.INSTANCE_PATH}}"
