# Source: https://github.com/arduino/.github/blob/master/workflow-templates/unit-tests.yml
name: Unit Tests

# See: https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows
on:
  pull_request:
    paths:
      - ".github/workflows/unit-tests.yml"
      - "extras/test/**"
      - "src/**"
  push:
    paths:
      - ".github/workflows/unit-tests.yml"
      - "extras/test/**"
      - "src/**"
  workflow_dispatch:
  repository_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      COVERAGE_DATA_PATH: extras/coverage-data/coverage.info

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: arduino/cpp-test-action@main
        with:
          runtime-paths: |
            # The list of unit test binary paths to run.
            - extras/test/build/bin/unit-test-binary
          coverage-exclude-paths: |
            - '*/extras/test/*'
            - '/usr/*'
            - '*/src/lib/*'
            # Additional paths to exclude from the coverage report can be added here.
          coverage-data-path: ${{ env.COVERAGE_DATA_PATH }}

      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: ${{ env.COVERAGE_DATA_PATH }}
          fail_ci_if_error: true
