# Source: https://github.com/arduino/.github/blob/master/workflow-templates/assets/check-markdown-task/Taskfile.yml
# See: https://taskfile.dev/#/usage
version: "3"

tasks:
  markdown:lint:
    desc: Check for problems in Markdown files
    cmds:
      - npx markdownlint-cli "**/*.md"

  # NOTE: npx --call uses the native shell, so this task can't be used on Windows.
  markdown:check-links:
    desc: Check for broken links
    cmds:
      - |
        npx --package=markdown-link-check --call='
        STATUS=0
        for file in $(find -name "*.md"); do
          markdown-link-check \
            --quiet \
            --config "./.markdown-link-check.json" \
            "$file"
          STATUS=$(( $STATUS + $? ))
        done
        exit $STATUS'
