# Source: https://github.com/arduino/.github/blob/master/workflow-templates/assets/check-packaging-ncc-typescript-task/Taskfile.yml
# See: https://taskfile.dev/#/usage
version: "3"

tasks:
  ts:install-deps:
    desc: Install TypeScript dependencies
    cmds:
      - npm install

  ts:build:
    desc: Build the action's TypeScript code.
    deps:
      - task: ts:install-deps
    cmds:
      - npx tsc
      - npx ncc build
