# Source: https://github.com/arduino/.github/blob/master/workflow-templates/assets/check-prettier-formatting-task/Taskfile.yml
# See: https://taskfile.dev/#/usage
version: "3"

tasks:
  general:format-prettier:
    desc: Format all supported files with Prettier
    cmds:
      - npx prettier --write .
