# See: https://taskfile.dev/#/usage
version: "3"

tasks:
  # Source: https://github.com/per1234/.github/blob/main/workflow-templates/assets/npm-task/Taskfile.yml
  npm:install-deps:
    desc: Install dependencies managed by npm
    cmds:
      - npm install
