# Source: https://github.com/arduino/.github/blob/master/workflow-templates/assets/spell-check-task/Taskfile.yml
# See: https://taskfile.dev/#/usage
version: "3"

tasks:
  general:check-spelling:
    desc: Check for commonly misspelled words
    cmds:
      - poetry install --no-root
      - poetry run codespell

  general:correct-spelling:
    desc: Correct commonly misspelled words where possible
    cmds:
      - poetry install --no-root
      - poetry run codespell --write-changes
