# Source: https://github.com/per1234/.github/blob/main/workflow-templates/check-python.md
name: Check Python

env:
  # See: https://github.com/actions/setup-python/tree/main#available-versions-of-python
  PYTHON_VERSION: "3.9"

# See: https://docs.github.com/en/actions/reference/events-that-trigger-workflows
on:
  push:
    paths:
      - ".github/workflows/check-python.ya?ml"
      - "**/.flake8"
      - "**/setup.cfg"
      - "**/tox.ini"
      - "**/poetry.lock"
      - "**/pyproject.toml"
      - "**.py"
  pull_request:
    paths:
      - ".github/workflows/check-python.ya?ml"
      - "**/.flake8"
      - "**/setup.cfg"
      - "**/tox.ini"
      - "**/poetry.lock"
      - "**/pyproject.toml"
      - "**.py"
  schedule:
    # Run every Tuesday at 8 AM UTC to catch breakage caused by changes to flake8.
    - cron: "0 8 * * TUE"
  workflow_dispatch:
  repository_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install flake8
        run: |
          python -m pip install --upgrade pip
          python -m pip install --quiet flake8
          python -m pip install --quiet pep8-naming

      - name: Run flake8
        run: python -m flake8 --show-source

  formatting:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Check formatting
        uses: psf/black@stable
