# Source: https://github.com/arduino/.github/blob/master/workflow-templates/check-typescript-npm.md
name: Check TypeScript

# See: https://docs.github.com/en/actions/reference/events-that-trigger-workflows
on:
  push:
    paths:
      - ".github/workflows/check-typescript-npm.ya?ml"
      - "**/.eslintrc*"
      - "package.json"
      - "package-lock.json"
      - "tsconfig.json"
      - "**.[jt]sx?"
  pull_request:
    paths:
      - ".github/workflows/check-typescript-npm.ya?ml"
      - "**/.eslintrc*"
      - "package.json"
      - "package-lock.json"
      - "tsconfig.json"
      - "**.[jt]sx?"
  workflow_dispatch:
  repository_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install --only=dev

      - name: Lint
        run: npm run-script lint
