# Source: https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/check-dependencies-task.md
name: Check Dependencies

# See: https://docs.github.com/en/actions/reference/events-that-trigger-workflows
on:
  push:
    paths:
      - ".github/workflows/check-dependencies-task.ya?ml"
      - "config/license_finder.yml"
      - "doc/dependency_decisions.yml"
      - "Taskfile.ya?ml"
      # See: https://github.com/pivotal/LicenseFinder#activation
      - "Gemfile"
      - "requirements.txt"
      - "package.json"
      - "pom.xml"
      - "build.gradle"
      - "settings.gradle"
      - "bower.json"
      - "Podfile"
      - "Cartfile"
      - "workspace-state.json"
      - "rebar.config"
      - "[Ee]rlang.mk"
      - "mix.exs"
      - "packages/**"
      - "*.csproj"
      - "vendor/manifest"
      - "*/vendor/manifest"
      - "glide.lock"
      - "vendor/vendor.json"
      - "Gopkg.lock"
      - "go.mod"
      - "vendor.conf"
      - "yarn.lock"
      - "conanfile.txt"
      - "build.sbt"
      - "Cargo.lock"
      - "composer.lock"
  pull_request:
    paths:
      - ".github/workflows/check-dependencies-task.ya?ml"
      - "config/license_finder.yml"
      - "doc/dependency_decisions.yml"
      - "Taskfile.ya?ml"
      # See: https://github.com/pivotal/LicenseFinder#activation
      - "Gemfile"
      - "requirements.txt"
      - "package.json"
      - "pom.xml"
      - "build.gradle"
      - "settings.gradle"
      - "bower.json"
      - "Podfile"
      - "Cartfile"
      - "workspace-state.json"
      - "rebar.config"
      - "[Ee]rlang.mk"
      - "mix.exs"
      - "packages/**"
      - "*.csproj"
      - "vendor/manifest"
      - "*/vendor/manifest"
      - "glide.lock"
      - "vendor/vendor.json"
      - "Gopkg.lock"
      - "go.mod"
      - "vendor.conf"
      - "yarn.lock"
      - "conanfile.txt"
      - "build.sbt"
      - "Cargo.lock"
      - "composer.lock"
  workflow_dispatch:
  repository_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ruby # Install latest version

      - name: Install License Finder
        run: gem install license_finder

      - name: Install Task
        uses: arduino/setup-task@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          version: 3.x

      - name: Check for unapproved dependencies
        run: task --silent general:verify-deps
