# Source: https://github.com/per1234/.github/blob/main/workflow-templates/check-action-metadata.md
name: Check Action Metadata

# See: https://docs.github.com/en/actions/reference/events-that-trigger-workflows
on:
  push:
    paths:
      - ".github/workflows/check-action-metadata.ya?ml"
      - "action.ya?ml"
  pull_request:
    paths:
      - ".github/workflows/check-action-metadata.ya?ml"
      - "action.ya?ml"
  schedule:
    # Run every Tuesday at 8 AM UTC to catch breakage from changes to the JSON schema.
    - cron: "0 8 * * TUE"
  workflow_dispatch:
  repository_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download JSON schema for action.yml
        id: download-schema
        uses: carlosperate/download-file-action@v2
        with:
          # See: https://github.com/SchemaStore/schemastore/blob/master/src/schemas/json/github-action.json
          file-url: https://json.schemastore.org/github-action
          location: ${{ runner.temp }}/github-action-schema
          file-name: github-action.json

      - name: Install JSON schema validator
        run: sudo npm install --global ajv-cli

      - name: Validate action.yml
        # See: https://github.com/ajv-validator/ajv-cli#readme
        run: |
          ajv validate \
            --strict=false \
            -s "${{ steps.download-schema.outputs.file-path }}" \
            -d "action.yml"
