# Source: https://github.com/per1234/.github/blob/main/workflow-templates/compile-sketches.md
name: Compile Sketches

# See: https://docs.github.com/en/actions/reference/events-that-trigger-workflows
on:
  push:
    paths-ignore:
      - ".github/**"
      - "!.github/workflows/compile-sketches.ya?ml"
      - "**.adoc"
      - "**.jpg"
      - "**.md"
      - "**.png"
      - "**.txt"
  pull_request:
    paths-ignore:
      - ".github/**"
      - "!.github/workflows/compile-sketches.ya?ml"
      - "**.adoc"
      - "**.jpg"
      - "**.md"
      - "**.png"
      - "**.txt"
  schedule:
    # Run every Tuesday at 8 AM UTC to catch breakage caused by changes to external resources (libraries, platforms).
    - cron: "0 8 * * TUE"
  workflow_dispatch:
  repository_dispatch:

jobs:
  build:
    name: ${{ matrix.board.fqbn }}
    runs-on: ubuntu-latest

    env:
      SKETCHES_REPORTS_PATH: sketches-reports

    strategy:
      fail-fast: false

      matrix:
        board:
          # TODO: Add list of boards to compile for here:
          - fqbn: arduino:avr:uno
            # TODO: Define the board's platform dependencies here.
            # See: https://github.com/arduino/compile-sketches#platforms
            platforms: |
              - name: arduino:avr

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Compile examples
        uses: arduino/compile-sketches@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fqbn: ${{ matrix.board.fqbn }}
          platforms: ${{ matrix.board.platforms }}
          libraries: |
            # Disable the default behavior of installing the repository as a library.
            -
            # Additional library dependencies can be listed here.
            # See: https://github.com/arduino/compile-sketches#libraries
          sketch-paths: |
            - ${{ github.workspace }}
          enable-deltas-report: true
          sketches-report-path: ${{ env.SKETCHES_REPORTS_PATH }}

      - name: Save sketches report as workflow artifact
        uses: actions/upload-artifact@v3
        with:
          if-no-files-found: error
          path: ${{ env.SKETCHES_REPORTS_PATH }}
          name: ${{ env.SKETCHES_REPORTS_PATH }}
