# Source: https://github.com/per1234/.github/blob/main/workflow-templates/compile-sketches-private.md
name: Compile Sketches

# See: https://docs.github.com/en/actions/reference/events-that-trigger-workflows
on:
  push:
    paths-ignore:
      - ".github/**"
      - "!.github/workflows/compile-sketches-private.ya?ml"
      - "**.adoc"
      - "**.jpg"
      - "**.md"
      - "**.png"
      - "**.txt"
  pull_request:
    paths-ignore:
      - ".github/**"
      - "!.github/workflows/compile-sketches-private.ya?ml"
      - "**.adoc"
      - "**.jpg"
      - "**.md"
      - "**.png"
      - "**.txt"
  schedule:
    # Run every Tuesday at 8 AM UTC to catch breakage caused by changes to external resources (libraries, platforms).
    - cron: "0 8 * * TUE"
  workflow_dispatch:
  repository_dispatch:

env:
  SKETCHES_REPORTS_PATH: sketches-reports

jobs:
  build:
    name: ${{ matrix.board.fqbn }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read

    strategy:
      fail-fast: false

      matrix:
        board:
          # TODO: Add list of boards to compile for here:
          - fqbn: arduino:avr:uno
            # TODO: Arbitrary suffix used to give the sketches report artifact a unique filename.
            artifact-name-suffix: arduino-avr-uno
            # TODO: Define the board's platform dependencies here.
            # See: https://github.com/arduino/compile-sketches#platforms
            platforms: |
              - name: arduino:avr

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile examples
        uses: arduino/compile-sketches@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fqbn: ${{ matrix.board.fqbn }}
          platforms: ${{ matrix.board.platforms }}
          libraries: |
            # Disable the default behavior of installing the repository as a library.
            []
            # Additional library dependencies can be listed here.
            # See: https://github.com/arduino/compile-sketches#libraries
          sketch-paths: |
            - ${{ github.workspace }}
          enable-deltas-report: true
          sketches-report-path: ${{ env.SKETCHES_REPORTS_PATH }}

      - name: Save sketches report as workflow artifact
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          path: ${{ env.SKETCHES_REPORTS_PATH }}
          name: sketches-report-${{ matrix.board.artifact-name-suffix }}

  report-size-deltas:
    needs: build
    # Run even if some compilations failed.
    if: always() && github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - name: Download sketches reports artifact
        id: download-artifact
        continue-on-error: true # If compilation failed for all boards then there are no artifacts
        uses: actions/download-artifact@v4
        with:
          path: ${{ env.SKETCHES_REPORTS_PATH }}

      - name: Comment size deltas report to PR
        uses: arduino/report-size-deltas@v1
        # If actions/download-artifact failed, there are no artifacts to report from.
        if: steps.download-artifact.outcome == 'success'
        with:
          sketches-reports-source: ${{ env.SKETCHES_REPORTS_PATH }}
