# Source: https://github.com/arduino/.github/blob/master/workflow-templates/deploy-mkdocs.md
name: Deploy MkDocs Website

# See: https://docs.github.com/en/actions/reference/events-that-trigger-workflows
on:
  push:
    branches:
      # TODO: Replace "$default-branch" below with the default branch name if it was not replaced already.
      - $default-branch
    paths:
      - ".github/workflows/deploy-mkdocs.yml"
      - "mkdocs.yml"
      - "docs/**"
  workflow_dispatch:
  repository_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install MkDocs
        run: |
          python -m pip install --upgrade pip
          python -m pip install --quiet --requirement "${{ github.workspace }}/docs/requirements.txt"

      - name: Deploy website
        run: python -m mkdocs gh-deploy
