# Source: https://github.com/arduino/.github/blob/master/workflow-templates/test-cpp.md
name: Test C++

# See: https://docs.github.com/en/actions/reference/events-that-trigger-workflows
on:
  push:
    paths:
      - ".github/workflows/test-cpp.ya?ml"
      - "extras/test/**"
      - "src/**"
  pull_request:
    paths:
      - ".github/workflows/test-cpp.ya?ml"
      - "extras/test/**"
      - "src/**"
  workflow_dispatch:
  repository_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      COVERAGE_DATA_PATH: extras/coverage-data/coverage.info

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: arduino/cpp-test-action@v1
        with:
          runtime-paths: |
            # The list of unit test binary paths to run.
            - extras/test/build/bin/unit-test-binary
          coverage-exclude-paths: |
            - '*/extras/test/*'
            - '/usr/*'
            - '*/src/lib/*'
            # Additional paths to exclude from the coverage report can be added here.
          coverage-data-path: ${{ env.COVERAGE_DATA_PATH }}

      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: ${{ env.COVERAGE_DATA_PATH }}
          fail_ci_if_error: true
