# Source: https://github.com/per1234/.github/blob/main/workflow-templates/assets/check-action-metadata-task/Taskfile.yml
# See: https://taskfile.dev/#/usage
version: "3"

tasks:
  action:validate:
    desc: Validate GitHub Actions metadata against JSON schema
    vars:
      ACTION_METADATA_SCHEMA_PATH:
        sh: mktemp -t github-action-schema-XXXXXXXXXX.json
    cmds:
      - wget --quiet --output-document="{{.ACTION_METADATA_SCHEMA_PATH}}" https://json.schemastore.org/github-action
      - npx ajv-cli validate --strict=false -s "{{.ACTION_METADATA_SCHEMA_PATH}}" -d "action.yml"
