# This repository contains intentionally duplicated copies of files:
# - Workflow template copies in .github/workflows used for this repository's own CI system.
# - Assets for the workflow templates used in this repository.
#
# This workflow checks that the copies are in sync.
# If the workflow fails, run workflow-templates/etc/sync.sh and commit.

name: Check File Duplicates Sync

# See: https://docs.github.com/en/actions/reference/events-that-trigger-workflows
on:
  push:
  pull_request:

jobs:
  check-sync:
    runs-on: ubuntu-latest
    permissions: {}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check file duplicates sync
        run: |
          SYNC_SCRIPT_PATH="workflow-templates/etc/sync.sh"
          "${{ github.workspace }}/$SYNC_SCRIPT_PATH"
          git add .
          if ! git diff --color --exit-code HEAD; then
            echo "::error::File duplicates are out of sync. Please run $SYNC_SCRIPT_PATH"
            exit 1
          fi
